name: linux-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download ut.hpp
      run: |
        curl -O https://raw.githubusercontent.com/boost-ext/ut/master/include/boost/ut.hpp

    - name: build
      run: |
        g++ --version
        g++ -std=c++2b -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -o test test.cpp

    - name: run_tests
      run: ./test
